JTNewY/mungmoong

- mungmoong/src/main/java/com/mypet/mungmoong/board/controller/BoardController.java
- mungmoong/src/main/resources/templates/board/test.html
> board/test 작업함

- mungmoong/src/main/resources/templates/board/test.html
> tj - board/test 추가 작업

- mungmoong/src/main/java/com/mypet/mungmoong/admin/controller/AdminController.java
- mungmoong/src/main/resources/static/css/style.css
- mungmoong/src/main/resources/templates/admin/admin.html
- mungmoong/src/main/resources/templates/fragments/admin/link.html
- mungmoong/src/main/resources/templates/fragments/admin/script.html
- mungmoong/src/main/resources/templates/fragments/common/footer.html
- mungmoong/src/main/resources/templates/layouts/admin_layout.html
2024-05-23 어드민 페이지 추가 및 공통 스타일 일부 변경
> Lee tae won

- mungmoong/src/main/resources/templates/admin/admin_board.html
- mungmoong/src/main/resources/templates/admin/admin_info.html
- mungmoong/src/main/resources/templates/admin/admin_reserve.html
- mungmoong/src/main/resources/templates/admin/admin_trainer.html
> 2024-05-24 오전푸시

- mungmoong/src/main/resources/templates/layouts/reserve_layout.html
- mungmoong/src/main/resources/templates/reserve/insert.html
- mungmoong/src/main/resources/templates/reserve/list.html
- mungmoong/src/main/resources/templates/reserve/read.html
- mungmoong/src/main/resources/templates/reserve/update.html
> 예약페이지 crud수정

- mungmoong/src/main/resources/static/css/trainer.css
- mungmoong/src/main/resources/templates/fragments/trainer/link.html
- mungmoong/src/main/resources/templates/trainer/info.html
- mungmoong/src/main/resources/templates/trainer/info_update.html
- mungmoong/src/main/resources/templates/trainer/status.html
> 5월 24일 마지막 커밋

- mungmoong/src/main/resources/templates/admin/admin_board.html
- mungmoong/src/main/resources/templates/admin/admin_info.html
- mungmoong/src/main/resources/templates/admin/admin_info_read.html
- mungmoong/src/main/resources/templates/admin/admin_info_read_pet.html
- mungmoong/src/main/resources/templates/admin/admin_info_read_user.html
- mungmoong/src/main/resources/templates/admin/admin_reserve.html
- mungmoong/src/main/resources/templates/admin/admin_reserve_pay.html
- mungmoong/src/main/resources/templates/admin/admin_trainer.html
> 2024-05-27 정규수업 마지막 커밋

- mungmoong/src/main/java/com/mypet/mungmoong/main/controller/MainController.java
- mungmoong/src/main/resources/application.properties
- mungmoong/src/main/resources/templates/fragments/common/header.html
1. ReserveController 는 풀받으면 소문자로 받아져서 주의가 필요합니다
2. mainController.java 소개, 훈련사추가해서 페이지 보일수 있도록 수정했습니다 
결제페이지 수정시 경로가 필요해서..
> maincontroller.java 소개,훈련사 추가

- mungmoong/src/main/java/com/mypet/mungmoong/admin/mapper/AdminMapper.java
- mungmoong/src/main/java/com/mypet/mungmoong/admin/service/AdminService.java
- mungmoong/src/main/resources/static/css/admin.css
- mungmoong/src/main/resources/static/js/admin.js
- mungmoong/src/main/resources/templates/admin/admin_board.html
- mungmoong/src/main/resources/templates/admin/admin_board_read.html
- mungmoong/src/main/resources/templates/admin/admin_info.html
- mungmoong/src/main/resources/templates/admin/admin_info_read.html
- mungmoong/src/main/resources/templates/admin/admin_info_read_pet.html
- mungmoong/src/main/resources/templates/admin/admin_reserve.html
- mungmoong/src/main/resources/templates/admin/admin_trainer.html
- mungmoong/src/main/resources/templates/admin/admin_trainer_read.html
> 2024-05-28 점심먹고 와서 커밋

- mungmoong/sql/ddl.sql
- mungmoong/src/main/java/com/mypet/mungmoong/orders/controller/OrdersController.java
- mungmoong/src/main/java/com/mypet/mungmoong/orders/dto/OrdersDetail.java
- mungmoong/src/main/resources/templates/orders/orders.html
> 20240528 orders.html 예약입력 수정

- mungmoong/src/main/java/com/mypet/mungmoong/trainer/mapper/TrainerMapper.java
BoardMapper → TrainerMapper 로 변경 하위 안에 내용 이름 변경 확인 필요
> 2024-05-29 기존 파일명 수정 후 이름 변경

- mungmoong/src/main/java/com/mypet/mungmoong/users/controller/UsersController.java
- mungmoong/src/main/resources/static/js/register.js
- mungmoong/src/main/resources/templates/users/register.html
> alert 대신 label 출력으로 변경

- mungmoong/sql/ddl.sql
- mungmoong/sql/trainer.sql
> IMG_FILE USER_NO 왜 넣음?

- mungmoong/src/main/java/com/mypet/mungmoong/config/SecurityConfig.java
- mungmoong/src/main/java/com/mypet/mungmoong/security/LoginSuccessHandler.java
- mungmoong/src/main/java/com/mypet/mungmoong/users/controller/UsersController.java
- mungmoong/src/main/resources/static/css/login.css
- mungmoong/src/main/resources/templates/users/login.html
.successHandler(loginSuccessHandler) 수정 + login페이지 수정 + usercontroller get추가
> 아이디저장/ 자동로그인 수정

- mungmoong/sql/ddl.sql
- mungmoong/src/main/java/com/mypet/mungmoong/main/controller/MainController.java
- mungmoong/src/main/resources/application.properties
- mungmoong/src/main/resources/com/mypet/mungmoong/board/mapper/BoardMapper.xml
- mungmoong/src/main/resources/templates/QnA/insert.html
- mungmoong/src/main/resources/templates/QnA/read.html
- mungmoong/src/main/resources/templates/QnA/update.html
1. boardMapper.xml 수정
2.  오류메세지 -->There is no getter for property named 'no' in 'class com.mypet.mungmoong.board.dto.Board' 
Mapper.xml 에서 Board 객체에는no 와 no 게터 메소드가 없어서 나는 오류  #{no}--->#{boardNo}
SQL 쿼리문을 확인할 것
3. crud화면에 토큰값에 $표시 누락
4. 화면단에 input type="hidden" name="boardNo"으로 변경요망~
> 20240531[재희]게시판 수정

- mungmoong/src/main/java/com/mypet/mungmoong/trainermain/controller/TrainerMainController.java
- mungmoong/src/main/resources/templates/trainermain/insert.html
- mungmoong/src/main/resources/templates/trainermain/read.html
- mungmoong/src/main/resources/templates/trainermain/trainer.html
> 20240602[재희]훈련사페이지 crud수정

- mungmoong/src/main/java/com/mypet/mungmoong/trainermain/controller/TrainerMainController.java
- mungmoong/src/main/resources/com/mypet/mungmoong/users/mapper/UsersMapper.xml
- mungmoong/src/main/resources/templates/trainermain/list.html
> usersMapper.xml 수정

- mungmoong/src/main/java/com/mypet/mungmoong/config/SecurityConfig.java
- mungmoong/src/main/java/com/mypet/mungmoong/security/LoginSuccessHandler.java
- mungmoong/src/main/java/com/mypet/mungmoong/users/controller/UsersController.java
- mungmoong/src/main/java/com/mypet/mungmoong/users/dto/CustomUser.java
- mungmoong/src/main/java/com/mypet/mungmoong/users/dto/OAuthAttributes.java
- mungmoong/src/main/java/com/mypet/mungmoong/users/dto/UserSocial.java
- mungmoong/src/main/java/com/mypet/mungmoong/users/mapper/UsersMapper.java
- mungmoong/src/main/java/com/mypet/mungmoong/users/service/OAuthService.java
- mungmoong/src/main/java/com/mypet/mungmoong/users/service/OAuthServiceImpl.java
- mungmoong/src/main/java/com/mypet/mungmoong/users/service/UsersService.java
- mungmoong/src/main/java/com/mypet/mungmoong/users/service/UsersServiceImpl.java
- mungmoong/src/main/resources/application-oauth.properties
- mungmoong/src/main/resources/com/mypet/mungmoong/users/mapper/UsersMapper.xml
- mungmoong/src/main/resources/templates/users/login.html
> 카카오 로그인 성공

- mungmoong/sql/20240607_ddl/pet샘플.sql
- mungmoong/src/main/java/com/mypet/mungmoong/pet/controller/PetController.java
- mungmoong/src/main/java/com/mypet/mungmoong/pet/dto/Pet.java
- mungmoong/src/main/java/com/mypet/mungmoong/trainer/service/TrainerServiceImpl.java
- mungmoong/src/main/resources/com/mypet/mungmoong/pet/mapper/PetMapper.xml
- mungmoong/src/main/resources/templates/users/index.html
- mungmoong/src/main/resources/templates/users/petAdd.html
> 0607 12:53 push

- mungmoong/src/main/java/com/mypet/mungmoong/pet/controller/PetController.java
- mungmoong/src/main/java/com/mypet/mungmoong/pet/mapper/PetMapper.java
- mungmoong/src/main/java/com/mypet/mungmoong/pet/service/PetService.java
- mungmoong/src/main/java/com/mypet/mungmoong/pet/service/PetServiceImpl.java
- mungmoong/src/main/resources/com/mypet/mungmoong/pet/mapper/PetMapper.xml
- mungmoong/src/main/resources/templates/users/index.html
- mungmoong/src/main/resources/templates/users/petUpdate.html
> 0607 19:52 푸쉬

- mungmoong/src/main/java/com/mypet/mungmoong/orders/controller/ProductsController.java
- mungmoong/src/main/resources/templates/products/detail.html
- mungmoong/src/main/resources/templates/reply/list.html
> [재희]댓글 수정중

- mungmoong/src/main/resources/templates/products/detail.html
> [재희] 댓글 저장은되는데 목록으로 출력안됨

- mungmoong/src/main/java/com/mypet/mungmoong/QnA/controller/QnAController.java
- mungmoong/src/main/resources/com/mypet/mungmoong/QnA/mapper/QnAMapper.xml
- mungmoong/src/main/resources/static/css/product.css
- mungmoong/src/main/resources/templates/QnA/list.html
- mungmoong/src/main/resources/templates/QnA/read.html
- mungmoong/src/main/resources/templates/products/detail.html
- mungmoong/src/main/resources/templates/reply/list.html
> [재희] qna read창 댓글 추가
